blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDetailView, BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import HomeTemplateView, MailingListView, MailingCreateView, \
    MailingUpdateView, MailingDeleteView, MailingDetailView, ClientListView, \
    ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, \
    MessageDeleteView, mailing_cancel, mailing_activate, MailingTryListView

app_name = MailingConfig.name

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing_cancel/<int:pk>/', mailing_cancel, name='mailing_cancel'),
    path('mailing_activate/<int:pk>/', mailing_activate, name='mailing_activate'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_detail/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('mailing_try/<int:pk>/', MailingTryListView.as_view(), name='mailingtry_list'),
]

mailing/models.py
from django.db import models


# Create your models here.
class Client(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="имя клиента"
    )
    email = models.EmailField(
        max_length=100,
        verbose_name="email клиента"
    )
    comment = models.TextField(
        verbose_name="комментарий"
    )
    owner = models.ForeignKey(
        to="users.User",
        on_delete=models.CASCADE,
        verbose_name="пользователь"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"


class Message(models.Model):
    subject = models.CharField(
        max_length=150,
        verbose_name="тема сообщения"
    )
    message = models.TextField(
        verbose_name="сообщение"
    )
    owner = models.ForeignKey(
        to="users.User",
        on_delete=models.CASCADE,
        verbose_name="пользователь"
    )

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = "сообщение"
        verbose_name_plural = "сообщения"


class Mailing(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="название рассылки"
    )
    first_send_datetime = models.DateTimeField(
        verbose_name="дата первого отправления"
    )
    next_send_datetime = models.DateTimeField(
        verbose_name="дата следующего отправления"
    )
    last_send_datetime = models.DateTimeField(
        verbose_name="дата последнего отправления"
    )
    period_choices = (
        (1, 'Каждую минуту'),
        (60, 'Каждый час'),
        (1440, 'Ежедневно'),
        (10080, 'Еженедельно'),
        (43200, 'Ежемесячно(каждые 30 дней)'),
    )
    period = models.IntegerField(
        choices=period_choices,
        verbose_name="периодичность рассылки"
    )
    status_choices = (
        (0, 'Создана'),
        (1, 'Запущена'),
        (2, 'Отменена пользователем'),
        (3, 'Отменена персоналом'),
        (4, 'Завершена')
    )
    status = models.IntegerField(
        choices=status_choices,
        verbose_name="статус рассылки"
    )
    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        verbose_name="сообщение"
    )
    clients = models.ManyToManyField(
        Client,
        verbose_name="клиенты"
    )
    owner = models.ForeignKey(
        to="users.User",
        on_delete=models.CASCADE,
        verbose_name="пользователь"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "рассылка"
        verbose_name_plural = "рассылки"
        permissions = (
            ('mailing.can_change_mailing_status', 'Может изменять статус рассылки'),
            ('mailing.can_view_all_mailings', 'Может просматривать все рассылки'),
        )


class MailingTry(models.Model):
    try_datetime = models.DateTimeField(
        auto_now_add=True,
        verbose_name="время и дата попытки",
        editable=False
    )
    status = models.BooleanField(
        verbose_name="статус попытки",
        editable=False
    )
    response = models.TextField(
        null=True,
        verbose_name="ответ почтового сервера",
        editable=False
    )
    mailing = models.ForeignKey(
        Mailing,
        on_delete=models.CASCADE,
        verbose_name="рассылка"
    )
    client = models.ForeignKey(
        Client,
        on_delete=models.CASCADE,
        verbose_name="клиент"
    )

    def __str__(self):
        return (f'Попытка рассылки {self.pk} - {self.mailing} '
                f'- {self.try_datetime} - {self.status} - {self.client}')

    class Meta:
        verbose_name = "попытка отправки"
        verbose_name_plural = "попытки отправки"

mailing/forms.py
from django.forms import BooleanField, ModelForm
from django import forms
from mailing.models import Message, Client, Mailing


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['message'].queryset = Message.objects.filter(owner=self.instance.owner)
        self.fields['clients'].queryset = Client.objects.filter(owner=self.instance.owner)

    class Meta:
        model = Mailing
        fields = ['name', 'first_send_datetime',
                  'last_send_datetime', 'period', 'status', 'message',
                  'clients']
        widgets = {
            'first_send_datetime': forms.DateTimeInput(
                attrs={'type': 'datetime-local'}),
            'last_send_datetime': forms.DateTimeInput(
                attrs={'type': 'datetime-local'}),
            # multiple select for many-to-many relation
            'clients': forms.SelectMultiple(
                attrs={'multiple': True}),
        }

mailing/views.py
from datetime import timedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, \
    DeleteView, TemplateView

from mailing.forms import MailingForm
from mailing.models import Mailing, Client, Message, MailingTry
from mailing.services import get_uniq_clients_count, get_mailings_counts, \
    get_random_blogs
from mailing.tasks import activate_mailings


# Create your views here.

class HomeTemplateView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['uniq_clients'] = get_uniq_clients_count()
        context['mailings_count'], context[
            'active_mailings'] = get_mailings_counts()
        context['blog_list'] = get_random_blogs()
        return context


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self, *args, **kwargs):
        user = self.request.user
        if self.request.user.is_superuser or self.request.user.has_perm(
                'mailing.can_view_all_mailings'):
            return Mailing.objects.all()
        return Mailing.objects.filter(owner=user)


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = Mailing(owner=self.request.user)
        return kwargs

    def get_success_url(self):
        return reverse('mailing:mailing_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        mailing = form.save(commit=False)
        mailing.next_send_datetime = mailing.first_send_datetime
        mailing.owner = self.request.user
        mailing.save()
        activate_time = mailing.next_send_datetime - timedelta(minutes=5)
        activate_mailings.apply_async((mailing.id,), eta=activate_time)
        return super().form_valid(form)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm

    def form_valid(self, form):
        mailing = form.save(commit=False)
        mailing.next_send_datetime = mailing.first_send_datetime
        mailing.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mailing:mailing_detail', kwargs={'pk': self.object.pk})


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self, *args, **kwargs):
        user = self.request.user
        if self.request.user.is_superuser or self.request.user.has_perm(
                'mailing.can_see'):
            return Client.objects.all()
        return Client.objects.filter(owner=user)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ['name', 'email', 'comment']

    def get_success_url(self):
        return reverse('mailing:client_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        product = form.save(commit=False)
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client

    def get_object(self, queryset=None):
        obj = super().get_object()
        if self.request.user.is_superuser:
            return obj
        elif obj.owner != self.request.user:
            raise PermissionDenied('Вы не можете просматривать чужих клиентов')
        return obj


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ['name', 'email', 'comment']

    def get_success_url(self):
        return reverse('mailing:client_detail', kwargs={'pk': self.object.pk})


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    permission_required = 'mailing.can_see_messages'

    def get_queryset(self, *args, **kwargs):
        user = self.request.user
        if self.request.user.is_superuser or self.request.user.has_perm(
                'mailing.can_see'):
            return Message.objects.all()
        return Message.objects.filter(owner=user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ['subject', 'message']

    def get_success_url(self):
        return reverse('mailing:message_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        product = form.save(commit=False)
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message

    def get_object(self, queryset=None):
        obj = super().get_object()
        if self.request.user.is_superuser:
            return obj
        elif obj.owner != self.request.user:
            raise PermissionDenied('Вы не можете просматривать чужие сообщения')
        return obj


def mailing_cancel(request, pk):
    mailing = Mailing.objects.filter(pk=pk).first()
    if request.user == mailing.owner:
        mailing.status = 2
        mailing.save()
        return redirect('mailing:mailing_detail', pk=pk)
    elif request.user.is_superuser or request.user.has_perm(
            'mailing.can_change_mailing_status'):
        mailing.status = 3
        mailing.save()
        return redirect('mailing:mailing_detail', pk=pk)
    else:
        raise PermissionDenied(
            'Шуруй отседова, ПЁС(плюс пасхалка получается)))))))')


def mailing_activate(request, pk):
    mailing = Mailing.objects.filter(pk=pk).first()
    if mailing.status == 3 and request.user == mailing.owner:
        raise PermissionDenied('Обратитесь в поддержку сервиса')
    elif mailing.status == 2 and request.user == mailing.owner:
        mailing.status = 1
        mailing.save()
        return redirect('mailing:mailing_detail', pk=pk)
    elif request.user.is_superuser or request.user.has_perm(
            'mailing.can_change_mailing_status') and mailing.status == 3:
        mailing.status = 1
        mailing.save()
        return redirect('mailing:mailing_detail', pk=pk)
    else:
        raise PermissionDenied('Что-то пошло не так =(')


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    fields = ['subject', 'message']

    def get_success_url(self):
        return reverse('mailing:message_detail', kwargs={'pk': self.object.pk})


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')


class MailingTryListView(LoginRequiredMixin, ListView):
    model = MailingTry

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing_obj'] = Mailing.objects.filter(
            pk=self.kwargs['pk']).first()
        return context

    def get_queryset(self, *args, **kwargs):
        user = self.request.user
        if self.request.user.is_superuser:
            return MailingTry.objects.filter(mailing=self.kwargs['pk'])
        return MailingTry.objects.filter(mailing=self.kwargs['pk'])

mailing/templates/mailing/client_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента - {{ object.email}}?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-4 box-shadow">
    <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{client.name}}</h4>
    </div>
    <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>Почта клиента: {{ client.email }}</li>
        </ul>
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>Комментарий: {{ client.comment }}</li>
        </ul>
        <a class="btn btn-lg btn-block btn-warning" href="{% url 'mailing:client_update' object.pk %}">Изменить</a>
        <a class="btn btn-lg btn-block btn-danger" href="{% url 'mailing:client_delete' object.pk %}">Удалить</a>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        {% if object %}
                        <h3>Изменить описание клиента</h3>
                        {% else %}
                        <h3>Добавить клиента</h3>
                        {% endif %}
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-success">Сохранить
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-success">Создать
                        </button>
                        {% endif %}
                        {% if object %}
                        <a class="btn btn-primary "
                           href="{% url 'mailing:client_list' %}">Отмена</a>
                        {% else %}
                        <a class="btn btn-primary "
                           href="{% url 'mailing:client_list' %}">Отмена</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'base.html' %}
{% load to_100_symbols %}
{% load media_tag %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <a class="btn btn-outline-primary btb-right" href="{% url 'mailing:client_create' %}">Добавить клиента</a>
</div>
    </div>
    </div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Клиенты</h1>
</div>

<div class="container">

    <div class="row text-center">
        {% for client in object_list %}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        {{client.name}}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Почта клиента: {{ client.email }}</li>
                    </ul>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Комментарий: {{ client.comment }}</li>
                    </ul>
                    <a class="btn btn-mb btn-outline-primary"
                       href="{% url 'mailing:client_detail' client.pk %}">Подробности</a>
                    <hr>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку - {{ object.name}}?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-4 box-shadow">
    <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{mailing.name}}</h4>
    </div>
    <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>Время первого отправления: {{mailing.first_send_datetime}}</li>
        </ul>
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>Время следующей отправки: {{mailing.next_send_datetime}}</li>
        </ul>
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>Время окончания отправки: {{mailing.last_send_datetime}}</li>
        </ul>
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>Периодичность: {{mailing.get_period_display}}</li>
        </ul>
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>Статус: {{mailing.get_status_display}}</li>
        </ul>
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>Сообщение: {{mailing.message.message}}</li>
        </ul>
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>Клиенты для рассылки:
            {% for client in mailing.clients.all %}
            {{client.name}} - {{client.email}}|
            {% endfor %}</li>
        </ul>
        {% if mailing.status is 1 or mailing.status is 0 %}
        <a class="btn btn-lg btn-block btn-outline-danger" href="{% url 'mailing:mailing_cancel' mailing.pk %}">
            Деактивировать
        </a>
        {% elif mailing.status is 3 and user.is_superuser or mailing.status is 3 and perms.mailing.can_change_mailing_status or mailing.status is 2 %}
        <a class="btn btn-lg btn-block btn-success" href="{% url 'mailing:mailing_activate' mailing.pk %}">Активировать</a>
        {% endif %}
        <a class="btn btn-lg btn-block btn-primary" href="{% url 'mailing:mailingtry_list' mailing.pk %}">Перейти в логи</a>
        <a class="btn btn-lg btn-block btn-warning" href="{% url 'mailing:mailing_update' object.pk %}">Изменить</a>
        {% if user.is_superuser %}
        <a class="btn btn-lg btn-block btn-danger" href="{% url 'mailing:mailing_delete' object.pk %}">Удалить</a>
        {% endif %}
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        {% if object %}
                        <h3>Изменить параметры рассылки</h3>
                        {% else %}
                        <h3>Создать рассылку</h3>
                        {% endif %}
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-success">Сохранить
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-success">Создать
                        </button>
                        {% endif %}
                        {% if object %}
                        <a class="btn btn-primary "
                           href="{% url 'mailing:mailing_list' %}">Отмена</a>
                        {% else %}
                        <a class="btn btn-primary "
                           href="{% url 'mailing:mailing_list' %}">Отмена</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'base.html' %}
{% load to_100_symbols %}
{% load media_tag %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <a class="btn btn-outline-primary btb-right" href="{% url 'mailing:mailing_create' %}">Создать рассылку</a>
</div>
    </div>
    </div>
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылошная</h1>
    <p class="lead">Рассылошная - это отличный вариант заспамить клиента</p>
</div>

<div class="container">

    <div class="row text-center">
        {% for mailing in object_list %}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        {{mailing.name}}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Периодичность: {{ mailing.get_period_display }}</li>
                    </ul>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Статус: {{ mailing.get_status_display }}</li>
                    </ul>
                    <a class="btn btn-mb btn-outline-primary"
                       href="{% url 'mailing:mailing_detail' mailing.pk %}">Подробности</a>
                    <hr>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailingtry_list.html
{% extends 'base.html' %}
{% load to_100_symbols %}
{% load media_tag %}
{% block content %}
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Отчет по рассылке {{ mailing_obj.name}}</h1>
</div>

<div class="container">
    <div class="row text-center">
            <div class="col-12 card mb-4 box-shadow">
                <div class="card-body">
                    <table>
                      <thead>
                        <tr>
                          <th>Идентификационный номер</th>
                          <th>Рассылка</th>
                          <th>Статус</th>
                          <th>Время отправки</th>
                          <th>Email клиента</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for mailingtry in object_list %}
                        <tr>
                          <td>{{ mailingtry.id }}</td>
                          <td>{{ mailingtry.mailing.name }}</td>
                          {% if mailingtry.status %}
                            <td>Успешно</td>
                          {% else %}
                            <td>Ошибка</td>
                          {% endif %}
                          <td>{{ mailingtry.try_datetime }}</td>
                          <td>{{ mailingtry.client.email  }}</td>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить сообщение - {{ object.subject }}?</p>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                        <a href="{% url 'mailing:message_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-4 box-shadow">
    <div class="card-header">
        <h4 class="my-0 font-weight-normal">{{message.subject}}</h4>
    </div>
    <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>Текст: {{message.message}}</li>
        </ul>
        <a class="btn btn-lg btn-block btn-warning" href="{% url 'mailing:message_update' object.pk %}">Изменить</a>
        <a class="btn btn-lg btn-block btn-danger" href="{% url 'mailing:message_delete' object.pk %}">Удалить</a>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'base.html' %}
{% load to_100_symbols %}
{% load media_tag %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <a class="btn btn-outline-primary btb-right" href="{% url 'mailing:message_create' %}">Создать сообщение</a>
</div>
    </div>
    </div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сообщения</h1>
</div>

<div class="container">

    <div class="row text-center">
        {% for message in object_list %}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        {{ message.subject }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Текст: {{ message.message | to_100_symbols}}</li>
                    </ul>
                    <a class="btn btn-mb btn-outline-primary"
                       href="{% url 'mailing:message_detail' message.pk %}">Подробности</a>
                    <hr>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>

{% endblock %}