blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogDetailView, BlogListView

app_name = BlogConfig.name

urlpatterns = [
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name="заголовок")
    text = models.TextField(verbose_name="содержимое статьи")
    image = models.ImageField(upload_to='blog/', verbose_name="изображение", blank=True, null=True)
    view_count = models.PositiveIntegerField(default=0, editable=False, verbose_name="количество просмотров")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="дата создания")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from blog.models import Blog


# Create your views here.
class BlogListView(ListView):
    model = Blog
    paginate_by = 8


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load media_tag %}
{% block content %}
<div class="container flex-d justify-content-center">
<div class="col-10 card mb-4 box-shadow">
    <div class="card-header">
        <h4 class="my-0 font-weight-normal text-center">{{blog.title}}</h4>
        <a class="text-muted">{{blog.created_at}}</a>
        <p>
        <a class="text-muted text-right"> Просмотров: {{blog.view_count}}</a>
    </div>
    <div class="card-body">
        <div style="text-align:center">
        <img src="{{blog.image | media_tag }}" class="img-fluid">
            </div>
        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
            <li>{{ blog.text }}</li>
        </ul>
    </div>
</div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load to_100_symbols %}
{% load media_tag %}
{% block content %}
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог</h1>
</div>

<div class="container">
    <div class="row text-center">
        {% for blog in object_list %}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{blog.title}}</h4>
                </div>
                <div class="card-body">
                    <img src="{{blog.image | media_tag }}" class="card-img-top img-thumbnail">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ blog.text | to_100_symbols }}</li>
                    </ul>
                    <a class="btn btn-mb btn-outline-primary" href="{% url 'blog:blog_detail' blog.pk %}">Подробности</a>
                    <hr>
                    <a class="text-muted float-right">{{blog.view_count}}</a>
                </div>
            </div>
        </div>

        {% endfor %}

        {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if page_obj.previous_page_number > 1 %}
                <li class="page-item">
                    <a class="page-link"
                       href="{% url 'blog:blog_list' %}?page=1">
                        <span aria-hidden="true">1</span>
                    </a>
                </li>
                {% endif %}
                {% if page_obj.previous_page_number > 2 %}
                <li class="page-item"><a class="page-link">...</a></li>
                {% endif %}
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link"
                                         href="{% url 'blog:blog_list' %}?page={{ page_obj.previous_page_number}}">{{ page_obj.previous_page_number}}</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link">{{ page_obj.number}}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="{% url 'blog:blog_list' %}?page={{ page_obj.next_page_number}}">{{ page_obj.next_page_number}}</a></li>
                {% if page_obj.paginator.num_pages > page_obj.next_page_number|add:"1" %}
                <li class="page-item"><a class="page-link">...</a></li>
                {% endif %}
                {% endif %}
                {% if page_obj.paginator.num_pages > page_obj.next_page_number %}
                <li class="page-item">
                    <a class="page-link"
                       href="{% url 'blog:blog_list' %}?page={{ page_obj.paginator.num_pages}}">
                        <span aria-hidden="true">{{ page_obj.paginator.num_pages }}</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}

    </div>
</div>


{% endblock %}